CREATE TABLE DRUGS
(
    COMPANY_ID INTEGER NOT NULL,
    DRUG_ID INTEGER PRIMARY KEY NOT NULL,
    DRUG_NAME INTEGER NOT NULL,
    QUANTITY VARCHAR(50) NOT NULL
);
CREATE TABLE BATCHES
(
    BATCH_ID INTEGER PRIMARY KEY NOT NULL,
    DRUG_ID INTEGER FOREIGN KEY NOT NULL REFERENCES DRUG(DRUG_ID),
    EXP_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    MFG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
);